# Generated by Django 4.0 on 2024-11-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='imagel',
            new_name='image1',
        ),
    ]
